[workspace]
resolver = "3"
members = ["cal-debug", "cal-config", "cal-tauri", "cal-daemon"]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
tokio = { version = "1.44.2", features = ["full"] }
