[package]
name = "cal-config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
clap = { version = "4.5.37", features = ["derive"] }
directories-next = "2.0.0"
sys-locale = "0.3.2"
walkdir = "2.5.0"
