[package]
name = "cal-config"
version = "0.1.0"
edition = "2024"

[dependencies]
freedesktop-desktop-entry = "0.7.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
clap = { version = "4.5.37", features = ["derive"] }
directories-next = "2.0.0"
